language: go
sudo: false
addons:
  postgresql: 9.4
go:
  - 1.8
  - 1.9
  - tip
cache:
  directories:
  - samples
install:
  - go get github.com/urfave/cli
  - go get github.com/lib/pq
  - go get github.com/kennygrant/sanitize
  - go get github.com/cheggaaa/pb
  - go get github.com/JensRantil/go-csv
  - ./download_samples.sh
script:
  - go install && ./test.sh
  - go test
