language: go
os: linux
addons:
  postgresql: "9.4"
go:
  - "1.11"
  - tip
cache:
  directories:
  - samples
install:
  - ./download_samples.sh
script:
  - env GO111MODULE=on go install github.com/lukasmartinelli/pgfutter && ./test.sh
  - env GO111MODULE=on go test -v github.com/lukasmartinelli/pgfutter
